# Generated by Django 2.0.6 on 2019-08-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCategory',
            fields=[
                ('category_id', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('book_counts', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('category_pid', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'd_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DOrderiterm',
            fields=[
                ('shop_id', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('shop_bookid', models.DecimalField(decimal_places=0, max_digits=20)),
                ('shop_ordid', models.DecimalField(decimal_places=0, max_digits=20)),
                ('shop_num', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'd_orderiterm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingCar',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('book_id', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'shopping_car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('detail_address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('telphone', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
            options={
                'db_table': 't_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=255, null=True)),
                ('book_author', models.CharField(blank=True, max_length=255, null=True)),
                ('book_publish', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_time', models.CharField(blank=True, max_length=255, null=True)),
                ('book_intro', models.TextField(blank=True, null=True)),
                ('dd_price', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('book_size', models.CharField(blank=True, max_length=255, null=True)),
                ('paper', models.CharField(blank=True, max_length=255, null=True)),
                ('pack', models.CharField(blank=True, max_length=255, null=True)),
                ('whether_suit', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBook1',
            fields=[
                ('book_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=128)),
                ('book_author', models.CharField(max_length=64)),
                ('book_publish', models.CharField(max_length=128)),
                ('publish_time', models.DateField(blank=True, null=True)),
                ('revision', models.IntegerField(blank=True, null=True)),
                ('book_isbn', models.CharField(blank=True, max_length=64, null=True)),
                ('word_count', models.CharField(blank=True, max_length=64, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('open_type', models.CharField(blank=True, max_length=20, null=True)),
                ('book_paper', models.CharField(blank=True, max_length=64, null=True)),
                ('book_wrapper', models.CharField(blank=True, max_length=64, null=True)),
                ('book_category', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('book_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book_dprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('editor_recommendation', models.CharField(blank=True, max_length=2000, null=True)),
                ('content_introduction', models.CharField(blank=True, max_length=2000, null=True)),
                ('author_introduction', models.CharField(blank=True, max_length=2000, null=True)),
                ('menu', models.CharField(blank=True, max_length=2000, null=True)),
                ('media_review', models.CharField(blank=True, max_length=2000, null=True)),
                ('digest_image_path', models.CharField(blank=True, max_length=2000, null=True)),
                ('product_image_path', models.CharField(blank=True, max_length=2000, null=True)),
                ('series_name', models.CharField(blank=True, max_length=128, null=True)),
                ('printing_time', models.DateField(blank=True, null=True)),
                ('impression', models.CharField(blank=True, max_length=64, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('shelves_date', models.DateField(blank=True, null=True)),
                ('customer_socre', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('book_status', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('sales', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 't_book1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('num', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('create_date', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('order_addrid', models.DecimalField(decimal_places=0, max_digits=20)),
                ('order_uid', models.DecimalField(decimal_places=0, max_digits=20)),
                ('status', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
            ],
            options={
                'db_table': 't_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=20)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=30)),
                ('user_status', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
    ]
