# Generated by Django 2.0.6 on 2019-09-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id2', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('detail_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('telphone', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id2', models.IntegerField(blank=True, null=True)),
                ('column_6', models.CharField(blank=True, db_column='Column_6', max_length=20, null=True)),
            ],
            options={
                'db_table': 'user_address',
                'managed': False,
            },
        ),
    ]
