# Generated by Django 2.0.6 on 2019-09-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_bookid', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('shop_num', models.IntegerField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('column_6', models.CharField(blank=True, db_column='Column_6', max_length=20, null=True)),
            ],
            options={
                'db_table': 'orderitem',
                'managed': False,
            },
        ),
    ]
